services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    entrypoint: []
    command: sleep infinity
    image: compilerla/conventional-pre-commit:dev
    volumes:
      - ../:/home/compiler/src
